# Setup different operating systems
image:
  - macos-monterey
  - Ubuntu2204
  - Visual Studio 2022

# Target x86_64
platform: x64

for:
  - # Windows setup
    matrix:
      only:
        - image: Visual Studio 2022
    install:
      - cinst doxygen.install graphviz
    after_build:
      - cd %APPVEYOR_BUILD_FOLDER%
      - 7z a windows-x86_64.zip bin/unfolding.exe assets/html LICENSE README.md
    artifacts:
      - path: windows-x86_64.zip
        name: Windows-Release

  - # MacOS setup
    matrix:
      only:
        - image: macos-monterey
    install:
      - brew install doxygen graphviz
    after_build:
      - cd $APPVEYOR_BUILD_FOLDER
      - zip macos-x86_64.zip bin/unfolding assets/html LICENSE README.md
    artifacts:
      - path: macos-x86_64.zip
        name: MacOS-Release

  - # Linux setup
    matrix:
      only:
        - image: Ubuntu2204
    install:
      - sudo apt-get update
      - sudo apt-get install -y build-essential cmake doxygen graphviz libclang1-9 libclang-9-dev
    after_build:
      - cd $APPVEYOR_BUILD_FOLDER
      - zip linux-x86_64.zip bin/unfolding assets/html LICENSE README.md
    artifacts:
      - path: linux-x86_64.zip
        name: Linux-Release

# Create build directory and run CMake
before_build:
  - mkdir build
  - cd build
  - cmake ..

# Build program
build_script:
  - cmake --build . --target doxygen
  - cmake --build . --target install
